### PR TITLE
add RPT (Regenerates Points Token)

### PR DESCRIPTION
**Pull request by Lfh2msn**
add RPT (Regenerates Points Token)
Updated simplified Chinese translation

### CODE REVIEW

**Comment by Lfh2msn** [comment]
I don't know how to merge. fork it again and resubmit it.

**Comment by Lfh2msn** [comment]
branches should be created and submit it again? I don't know exactly what to do.

**Comment by kenodressel** [comment]
Can you provide us with a statement of the community / background / use of this token?

**Comment by Lfh2msn** [comment]
> Can you provide us with a statement of the community / background / use of this token?

It is styled by AE Chinese community, with no organization behind it. Its maximum circulation of 21 million, transfer =Mint, the initial Mint is 1, every reached 21 million 1/2, 3/4, 7/8 casting number will be correspondingly reduced to 1/2, 1/4, 1/8（0.5，0.25，0.125）

**Review by Lfh2msn — COMMENTED** [review]
src/locales/zh-cn.json

This simplified Chinese translation file I am sure works properly and it is the latest version. How should I submit it? Or can someone help me resubmit? It translates more accurately than the original document.

**Pull request merged**
